## Generate a ``closureManifest`` from an npm lock file.
##
## A package whose entry point does not run without its dependencies is
## realized by ``closureManifest``: a committed list of pinned archives that
## realize unpacks into the prefix. This is the tool that produces that
## list, so a dependency bump is a command rather than an afternoon of
## transcription.
##
## **Why it exists at all.** The manifest is derived data — every entry is
## the ``resolved`` URL npm already recorded, for the transitive closure of
## a package's ``dependencies``. Derived data that is regenerated by hand
## drifts from its source, and the drift is invisible until something fails
## to start. Writing the derivation down makes the manifest reviewable
## (it diffs like a lock file) AND reproducible.
##
## **The one thing it cannot take from the lock file.** npm pins by sha512
## ``integrity``; reprobuild verifies sha256. So each archive is fetched
## once and hashed. That is also a check worth having: it proves the URL
## npm recorded still serves bytes, at the moment the manifest is written.
##
## Usage::
##
##   just closure-manifest \
##     LOCK=../agent-harbor/scripts/agent-tools/package-lock.json \
##     ROOT=@zed-industries/claude-code-acp \
##     OUT=packages/vendor/claude-code-acp/closures/claude-code-acp.manifest
##
## ``--platform=<npm-os>-<npm-cpu>`` additionally follows
## ``optionalDependencies`` and keeps only the entries whose ``os``/``cpu``
## constraints admit that platform, which is how a package whose native
## binary arrives through npm's optional-dependency mechanism gets one
## manifest per reprobuild platform slice.

import std/[algorithm, json, os, osproc, sets, strformat, strutils, tables]

import repro_attest/measurement

type
  ClosureEntry = object
    path: string
    url: string

proc die(message: string) =
  stderr.writeLine("npm-closure-manifest: " & message)
  quit(1)

proc lockEntry(packages: JsonNode; name: string): JsonNode =
  let key = "node_modules/" & name
  if packages.hasKey(key): packages[key] else: nil

proc admits(entry: JsonNode; platform: string): bool =
  ## npm records ``os`` and ``cpu`` constraints on a platform-specific
  ## package. An entry with neither is universal.
  ##
  ## Empty ``platform`` means "take everything", which is right for a
  ## closure whose members are all JavaScript.
  if platform.len == 0:
    return true
  let parts = platform.split('-')
  if parts.len != 2:
    die("--platform must be <npm-os>-<npm-cpu>, e.g. win32-x64")
  for (field, want) in {"os": parts[0], "cpu": parts[1]}:
    if not entry.hasKey(field):
      continue
    var matched = false
    for value in entry[field]:
      if value.getStr() == want:
        matched = true
        break
    if not matched:
      return false
  true

proc closureOf(packages: JsonNode; root, platform: string): seq[ClosureEntry] =
  var seen = initHashSet[string]()
  var stack = @[root]
  var found = initTable[string, JsonNode]()
  while stack.len > 0:
    let name = stack.pop()
    if name in seen:
      continue
    let entry = lockEntry(packages, name)
    if entry.isNil:
      # A dependency the lock file does not carry is a broken lock, not a
      # thing to skip quietly: the manifest would be short by exactly the
      # package nothing can resolve.
      die("not in the lock file: " & name)
    if not entry.admits(platform):
      continue
    seen.incl(name)
    found[name] = entry
    for kind in ["dependencies", "optionalDependencies"]:
      # Optional dependencies are followed only under an explicit
      # --platform, because that is the only case where one of them is a
      # REQUIRED member of the closure rather than a nicety npm may skip.
      if kind == "optionalDependencies" and platform.len == 0:
        continue
      if entry.hasKey(kind):
        for dep, _ in entry[kind].pairs:
          stack.add(dep)
  for name, entry in found.pairs:
    if name == root:
      continue   # the root archive is the package's own `tarball url`
    if not entry.hasKey("resolved"):
      die("lock entry has no `resolved` url: " & name)
    result.add(ClosureEntry(path: "node_modules/" & name,
      url: entry["resolved"].getStr()))
  result.sort(proc (a, b: ClosureEntry): int = cmp(a.path, b.path))

proc sha256OfUrl(url, scratch: string): string =
  ## Fetched with ``curl`` rather than an in-process client on purpose:
  ## this tool runs when a dependency changes, not in a build, and
  ## shelling out keeps it free of a TLS build flag that every other tool
  ## in this repository does without.
  let target = scratch / "download.tgz"
  removeFile(target)
  let res = execCmdEx("curl -sSL --retry 2 -o " & quoteShell(target) & " " &
    quoteShell(url))
  if res.exitCode != 0 or not fileExists(target):
    die("download failed: " & url & "\n" & res.output)
  sha256Hex(readFile(target))

when isMainModule:
  var lockPath, root, outPath, platform = ""
  for i in 1 .. paramCount():
    let arg = paramStr(i)
    if arg.startsWith("--lock="): lockPath = arg["--lock=".len .. ^1]
    elif arg.startsWith("--root="): root = arg["--root=".len .. ^1]
    elif arg.startsWith("--out="): outPath = arg["--out=".len .. ^1]
    elif arg.startsWith("--platform="): platform = arg["--platform=".len .. ^1]
    else: die("unknown argument: " & arg)
  if lockPath.len == 0 or root.len == 0 or outPath.len == 0:
    die("usage: --lock=<package-lock.json> --root=<name> --out=<manifest> " &
      "[--platform=<npm-os>-<npm-cpu>]")
  if not fileExists(lockPath):
    die("no lock file at " & lockPath)

  let lock = parseFile(lockPath)
  if not lock.hasKey("packages"):
    die("not a lockfileVersion 2/3 lock file (no `packages`): " & lockPath)
  let entries = closureOf(lock["packages"], root, platform)
  if entries.len == 0:
    die("closure of " & root & " is empty; nothing to write")

  let scratch = getTempDir() / "npm-closure-manifest"
  createDir(scratch)

  var lines: seq[string] = @[]
  for i, entry in entries:
    stderr.writeLine(&"[{i + 1}/{entries.len}] {entry.path}")
    lines.add(entry.path & " " & sha256OfUrl(entry.url, scratch) & " " &
      entry.url)

  var header = @[
    "# Dependency closure for " & root & ".",
    "#",
    "# GENERATED by tools/npm_closure_manifest.nim -- do not hand-edit.",
    "# Every entry is the `resolved` URL npm recorded in",
    "#   " & lockPath,
    "# for the transitive closure of this package's dependencies, with the",
    "# sha256 of the archive that URL actually serves. npm pins by sha512",
    "# `integrity` and reprobuild verifies sha256, so each archive was",
    "# fetched once and hashed.",
    "#",
    "# Format (see TarballProvisioningDef.closureManifest):",
    "#   <prefix-relative-path> <sha256> <url>"]
  if platform.len > 0:
    header.add("#")
    header.add("# Platform-filtered for " & platform & ": optional")
    header.add("# dependencies are followed and entries whose npm os/cpu")
    header.add("# constraints exclude this platform are omitted.")
  createDir(parentDir(outPath))
  writeFile(outPath, (header & lines).join("\n") & "\n")
  try: removeDir(scratch) except CatchableError: discard
  stderr.writeLine(&"wrote {entries.len} entries to {outPath}")
